title: blog.mailson.org
timezone: America/Recife
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
