# Blog configuration
title: blog.mailson.org
author: "Mailson Menezes"
url: "http://blog.mailson.org"
baseurl: ""
timezone: America/Recife

google_analytics_id: "UA-31218644-1"

comments: true
disqus_shortname: "blogmailsonorg"

# Posts configuration
permalink: /:year/:month/:title.html
excerpt_separator: "\n\n+++\n\n"
paginate: 5
paginate_path: /page:num/

feed_limit: 10

# Social configuration
facebook_username: omailson
twitter_username: omailson
linkedin_username: mailson
github_username: omailson

facebook_appid: "784598104972753"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
