title: blog.mailson.org
url: ""
baseurl: ""
timezone: America/Recife
permalink: /:year/:month/:title.html
excerpt_separator: "\n\n+++\n\n"
paginate: 5
paginate_path: /page:num/

facebook_username: omailson
twitter_username: omailson
linkedin_username: mailson
github_username: omailson

facebook_appid: ""

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
